# Generated by Django 4.0.1 on 2022-01-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp2022', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comp2022.exercise'),
        ),
    ]
